@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant AI
participant Async
participant Worker
control ToolsContinuation
entity ToolDispatch1
entity ToolDispatch2
participant Dispatcher

AI -> Worker: tool1, tool2
Worker -> ToolsContinuation: dispatch: tool1, tool2

== Done at once ==
create ToolDispatch1
ToolsContinuation -> ToolDispatch1: create
ToolsContinuation -> ToolDispatch1: set call: tool1
ToolsContinuation -> Dispatcher: run: tool1, token1
ToolsContinuation <-- Dispatcher: data
ToolsContinuation -> ToolDispatch1: set data: tool1

== Done async ==
create ToolDispatch2
ToolsContinuation -> ToolDispatch2: create
ToolsContinuation -> ToolDispatch2: set call: tool2
ToolsContinuation -> Dispatcher: run: tool2, token2
Dispatcher -> Async: token2
ToolsContinuation <-- Dispatcher: SUSPENDED
Worker <- ToolsContinuation: complete

... some time later ...

Async -> ToolsContinuation: resume token2, data
ToolsContinuation -> ToolDispatch2: set data: tool2
ToolsContinuation -> Worker: tool result: data1, data2
Worker -> AI: run: data1, data2

@enduml