@startuml
'https://plantuml.com/use-case-diagram

:User:
(App)
User -> (App): observes
(App) -> (Cloud function): calls
(Cloud function) <--> (OpenAI): runs
(Cloud function) -> (Firestore): stores
(Firestore) .> (App): updates

@enduml